/// Flutter icons FlutterCustom
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterCustom
///      fonts:
///       - asset: fonts/FlutterCustom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FlutterCustom {
  FlutterCustom._();

  static const _kFontFam = 'FlutterCustom';

  static const IconData class_plus = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData school_plus = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData student_plus = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData class_manage = const IconData(0xe803, fontFamily: _kFontFam);
}
